### ISSUE TITLE
Hovering over sample name should be brand blue

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#1015]
Right now it's still the light blue from before
![Screen Shot 2018-03-20 at 2.55.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f36b7191a37af1172e4f5c585ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae44556a41b3667e47f2431.png)

**Comment by eggerdesigns** [comment]
![Screen Shot 2018-03-20 at 2.44.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f36b7191a37af1162f4f5d565ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae44556a4173f61e6702431.png)

**Comment by eggerdesigns** [comment]
Oops wrong screenshot above

**Comment by sadelokiki** [comment]
what the last issue was referring to was on the reports page, the link tags - will fix this one now

**Comment by eggerdesigns** [comment]
I still haven't seen a change to this in the most recent version of prod?

**Comment by sadelokiki** [comment]
done
