### ISSUE TITLE
"Batch" column in metadata?

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-web#1026]
To distinguish batches within a project, e.g. nucleic acid extraction batch, library prep batch, sequencing batch

**Comment by cdebourcy** [comment]
This will be great for IDseq encouraging reproducible science! Batch effects are a major problem but a lot of people don't spend the effort to look at them. This feature (when propagated to the heatmap) will make it totally easy to look at them!

**Comment by eggerdesigns** [comment]
@cdebourcy Still trying to get this info from Chaz and Emily.
