### ISSUE TITLE
Don't fail entire run if Rapsearch fails

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#1049]
I've been thinking in general it might be useful when rapsearch fails for a chunk to emit those reads as matching a special fake species with name "failed alignment", and if those are present, the webapp can surface that on the sample details page and also at the top of the report page.   Better than just failing the whole sample and not even seeing the gsnap results.

**Comment by boris-dimitrov** [comment]
Good idea, and we should make very certain that those fake taxons are not present in any background so they rise to the top of the page :P)  because it's usually bugs we should fix and rerun the chunk.   Alternatively we can have some "percent reads lost due to operational errors" warning.
