### ISSUE TITLE
Wonky checkbox behavior when Filters is open

### ISSUE THREAD

**Issue by jshoe** [chanzuckerberg/idseq-web#1088]
Bit of an edge case but something might be wrong in the JS checkbox logic (clicking the Sample checkbox can change checkboxes in the Filters dropdown?)

![mar-29-2018 09-40-49](https://user-images.githubusercontent.com/5652739/38101532-62439e14-3335-11e8-862e-7a892f1b468a.gif)

**Comment by cdebourcy** [comment]
wow

**Comment by cdebourcy** [comment]
@yunfangjuan ?

**Comment by cdebourcy** [comment]
we're in big trouble with this. If you go to project 30 and try to select the first two samples, all samples disappear and the filter dropdown opens

**Comment by jshoe** [comment]
repro'ed: checking just the 2nd sample seems to trigger the breakdown

**Comment by cdebourcy** [comment]
@jshoe bug first appeared here: https://github.com/chanzuckerberg/idseq-web/commit/171bb32fda375139da129c5a75980291151db871
:)
