### ISSUE TITLE
Update design of home page/sample page to look like Mocks

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#1165]
Current Design
![Screen Shot 2018-04-10 at 4.26.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a37cf1102d4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19e41c95df448e54d57ac133466e77f2431.png)

New Design
![Screen Shot 2018-04-10 at 4.27.10 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a37cf1102c4f5e5f5ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19e41c95df448e54d57ac17366ae1762431.png)

**Comment by jshoe** [comment]
@eggerdesigns did you still want the bolded text and the Non-Host Read count percentages on a different line? Should the run durations be simplified too?
