### ISSUE TITLE
s3_preload_result_path functionality is no longer current

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-web#1263]
after result folder versioning

not urgent but may be cleanup somehow as part of future lazy work

cc @yunfangjuan

**Comment by cdebourcy** [comment]
The preload functionality for admins used to be super helpful and I still replicate it ad hoc for tests. I think it would be a good idea to convert it into a "clone sample" functionality for admins (that works across environments), where you just give it the top-level path (e.g. s3://idseq-samples-alpha/samples/1/11/) and it copies the fastq inputs as well as the prior results for you. What do you think?
