### ISSUE TITLE
[security/privacy] any user can gain access to another user input fastqs by guessing the path

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-web#1282]
Virtually every input is s3://idseq-samples-production/samples/<project_id>/<sample_id>fastqs/<sample_name>.fastq.gz where the project id and sample id and sample name are obvious from urls when browsing the tool.   So I can submit a sample with inputs that are the same as some other user's inputs, and specify no host filtering, then recover all the dna.

cc @eggerdesigns @jameshowardwang

**Comment by boris-dimitrov** [comment]
Also are these issues visible to the public?   Should security issues be visible?

**Comment by boris-dimitrov** [comment]
I am not referring to presigned URLS but to paths s3://idseq-samples-production/samples/<project_id>/<sample_id>fastqs/<sample_name>.fastq.gz that contain no hahses and generally follow a prescribed pattern.   By some that would be considered easy to guess.    I think actually that's a fairly common opinion.  I understand if you disagree.  I am not in any way implying that this requires immediate action.  It is however something to consider if we ever decide to allow non-consented data as input, and then preclude access to the non-filtered fastqs.  In that case this may be considered a more signifficant loophole.  I don't know if it will occur to me again, so I wanted to note it in an issue.

**Comment by cdebourcy** [comment]
@boris-dimitrov like https://github.com/chanzuckerberg/idseq-web/pull/1285 ? Although we may want a deeper fix
