### ISSUE TITLE
Sample page won't load for some old samples

### ISSUE THREAD

**Issue by jshoe** [chanzuckerberg/idseq-web#1322]
- See: https://idseq.net/samples/2340 and related samples in that project. Page won't load.
- Console says: "Cannot read property 'id' of null at PipelineSampleReads.value."
- Not sure if it's like we don't have results for those projects or maybe a db error?

**Comment by cdebourcy** [comment]
Seems like this is a case of the sample's project having been deleted

**Comment by jshoe** [comment]
Hm ok I don't think we need to bother with this then
