### ISSUE TITLE
migration lost the favicon

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-web#1323]
![screen shot 2018-05-24 at 1 48 59 pm](https://user-images.githubusercontent.com/16944816/40512960-3d3b6dd6-5f59-11e8-935a-7ebe5063f137.png)
![screen shot 2018-05-24 at 1 48 53 pm](https://user-images.githubusercontent.com/16944816/40512966-3fc624e2-5f59-11e8-8bbb-790fa19785dd.png)

**Comment by jameshowardwang** [comment]
fixed - probably had to do with funny DNS stuff during the transition
