### ISSUE TITLE
Console error NaN

### ISSUE THREAD

**Issue by jshoe** [chanzuckerberg/idseq-web#1381]
![screen shot 2018-07-13 at 2 55 58 pm](https://user-images.githubusercontent.com/5652739/42715688-ecefedd6-86ac-11e8-968c-d1df968a64b2.png)

- Not sure if this console error is causing slow page loads or if staging is just under load for some reason

**Comment by tfrcarvalho** [comment]
Seem unrelated.
Can you send the url w/ parameters to see if can replicate?

**Comment by jshoe** [comment]
https://staging.idseq.net/samples/875?pipeline_version=2.4&background_id=4

**Comment by jshoe** [comment]
yeah it doesn't seem slow anymore.. should be fine
