### ISSUE TITLE
Impose date range selection in function fill_lineage_details

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-web#1413]
See https://github.com/chanzuckerberg/idseq-web/blob/27b5d2a9f64e7ffbc1e64df04dfe067b4ecf9b9a/app/models/taxon_lineage.rb#L42 

The where clause also needs to specify that the taxon_lineages' `started_at` and `ended_at` need to be smaller and greater than the taxon_counts' `created_at` value respectively.

**Comment by jshoe** [comment]
@cdebourcy so are there a lot of lineage records with a blank ended_at and started_at? or do all the current records have a "started_at" column?

**Comment by cdebourcy** [comment]
If started_at / ended_at is blank, it means +/- infinity. In particular, if ended_at is blank, it means the entry is currently the right one for taxon_counts that are being generated today.
This the condition we need to use to determine which TaxonLineage entry to use for a taxid: https://github.com/chanzuckerberg/idseq-web/blob/master/app/models/pipeline_run.rb#L675
