### ISSUE TITLE
Studentized residual approach

### ISSUE THREAD

**Issue by bcpd** [chanzuckerberg/idseq-web#2398]
Hello all,

I'm interested in trying out the studentized residual approach of Zinter et al. 2019 Microbiome 7:62. Where do I start?

Thanks much.

**Comment by katrinakalantar** [comment]
IDseq provides estimates of microbial abundances from NGS experiments and the Zinter et al. approach takes these values to estimate background contamination. If you are interested in using IDseq outputs of microbial abundance for the Zinter et al. approach, we would encourage you to sign up at https://idseq.net/ as a first step.
