### ISSUE TITLE
Create modal that lists project members

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#496]
Modal should show all members of a current project and give the user the option to remove users if they want.
![member-modal.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46e59197218791e482e6bb42a81fbcd6395428792c07b7692ac7b629ea157d55095b1af8460a5816fcf98f2aafbe3c268d0f19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bd8c4ac5e93d20ee8a874b2c53.png)
![Screen Shot 2018-01-30 at 11.26.37 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f36b7191a379ee0c2957415c49bc30254d58eeb9cb74fce36f34985619e880685822c26b15f8ec854db853ba208d4e8cbebcdc4b93fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae64e51a4173766e573316e0a.png)

**Comment by cdebourcy** [comment]
@eggerdesigns 
Food for thought -- if I create a project and add you to it, should you be able to remove me later?

**Comment by cdebourcy** [comment]
Maybe we need "project admins". Or at least just make a difference between creator of a project and users added later

**Comment by eggerdesigns** [comment]
@cdebourcy I totally agree. But let's start with something simple right now.

**Comment by eggerdesigns** [comment]
@cyrielo Just added a new screenshot. We want to be able to see suggestions when you start typing in a name of a user that already exists. The user list should show up as you start typing to help suggest users that already exist on IDseq. Just uploaded a screenshot of what I mean. @cdebourcy unclear if this is on the front-end or back-end side....

**Comment by cdebourcy** [comment]
@eggerdesigns :
@yunfangjuan, Ryan and I just had a little discussion and the outcome was that we shouldn't have a type-ahead for the user emails... it makes it too easy for anyone who's logged in to get a list of our entire user base which would be undesirable
