### ISSUE TITLE
Implement list of projects members on front end

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#501]
Call the function 'Can Edit' to the front-end so we can see the member list for a project. 
Call the function 'Can See' to the front-end so we can see the permission settings for a project.

**Comment by cdebourcy** [comment]
Partially addressed this in https://github.com/chanzuckerberg/idseq-web/pull/528.
Current project members are listed in the modal that opens when you click "Share project". Obviously to get there in the first place the project had to be visible to you.
