### ISSUE TITLE
sorted column is not bolded

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#510]
[asset migration bug] Score is always bold no matter what column your sorting on

**Comment by yunfangjuan** [comment]
Is this a problem on alpha?

**Comment by cyrielo** [comment]
I think that was the original design as on production.

**Comment by eggerdesigns** [comment]
I actually don't see it in prod either. So changing the milestone from asset migration and instead labeling it UI updates.
