### ISSUE TITLE
Category of genus/species no longer appears in report page

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#512]
See attachments for expected state vs. bug

![Screen Shot 2018-01-23 at 5.20.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f06b7191a37df1102b4f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19141c95df74de64853ad163360e7702431.png)
![Screen Shot 2018-01-23 at 5.21.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f06b7191a37df1102a4f5f565ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19141c95df74de64853ad153e67e1712431.png)

**Comment by yunfangjuan** [comment]
in alpha. fixed by @cyrielo
