### ISSUE TITLE
Add to sidebar - Your Projects

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#546]
Remove duplicates from your projects, favorites, and all projects.

**Comment by sadelokiki** [comment]
hey @eggerdesigns, what duplicates should be removed here?

**Comment by eggerdesigns** [comment]
Right now if a project is in your favorite it also shows up in the project list. We don't need to show both your favorite projects AND repeat the name in the project list. 

Instead sidebar should look like: 
All Samples
Favorite Projects
- A
- B
- C
Your Projects <-- these are projects you are a member of
- D
- E
- F
Public Projects <-- Public projects you are not a member of. 
- G
- H
- I

**Comment by sadelokiki** [comment]
got it
