### ISSUE TITLE
Change link to download files from going to s3 bucket to page with all file download

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#570]
Before on the details page the link that shows you all files takes you to an S3 bucket. 
Now that we are changing permissions we want that to go to the page with all the files the user can download from the pipeline run.

**Comment by sadelokiki** [comment]
@eggerdesigns @cyrielo, does this page with all files that can be downloaded exist already?

**Comment by sadelokiki** [comment]
i assume you are referring to the button that says "navigate to results folder"? @eggerdesigns

**Comment by eggerdesigns** [comment]
Yes I am - I just didn't think it was hooked up. On Alpha it still took me to the S3 bucket when it should go to the new page that you styled and worked on with Yun-Fang

**Comment by sadelokiki** [comment]
oh that page? alright then

**Comment by sadelokiki** [comment]
@eggerdesigns, so I just hooked them up in issue 489, since it is a very related PR, so we might not need to keep this issue.
