### ISSUE TITLE
job ignores STAR_genome parameter

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-web#581]
In the sample submission form I selected Mosquito host and this is reflected in the job description in AWS batch but when the job actually runs it pulls from S3 the human STAR genome.   See job id 03e5f3f6-fa94-4d78-a22d-5c91f2e15092 and sample 301 on alpha.

**Comment by boris-dimitrov** [comment]
The bug is quite obvious in the code.   It first gets the value from the environment variable, but then overwrites it with a constant (human genome).

**Comment by cdebourcy** [comment]
@boris-dimitrov yep... another bug I missed in the recent pipeline refactoring, thanks for pointing it out. Luckily recent users have only been using the human genopme

**Comment by boris-dimitrov** [comment]
No worries, my re-re-factoring is great for catching bugs ;)    I am testing the fix in https://github.com/chanzuckerberg/idseq-pipeline/pull/45/commits/d711ef3d1cacb585dc24f1c25afeb4b1601be131

**Comment by boris-dimitrov** [comment]
Looks like STAR is now running correctly on a mosquito multipart genome:   https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/batch/job;stream=aegea_batch/default/8911f07f-813c-4336-98b2-1d523cf0522f

**Comment by boris-dimitrov** [comment]
Fix merged.
