### ISSUE TITLE
Fix search bar design to be consistent with previous design

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#588]
Extend search bar to buttons, don't leave white space when there isn't a download report button.
![Screen Shot 2018-02-02 at 4.11.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f16b7191a37cf1132a4f5d575ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ce74c53a3143466e6712431.png)
![Screen Shot 2018-02-02 at 4.11.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f16b7191a37cf1132a4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ce74c53a3143261e67f2431.png)

**Comment by cyrielo** [comment]
Oh I didn't see the details of this issue, I created another issue related to this and has been resolved, there's an open PR for this #596
