### ISSUE TITLE
Make single sample upload modal the same width as the batch upload modal

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#590]
The batch upload modal is nice and big and makes the form much easier to read - can we make the single sample upload the same width?

**Comment by cdebourcy** [comment]
On a similar note:
<img width="1035" alt="screen shot 2018-02-07 at 6 36 59 pm" src="https://user-images.githubusercontent.com/16944816/35952661-edd038ba-0c35-11e8-9575-62fa4112b00e.png">

**Comment by cyrielo** [comment]
This issue was resolved https://github.com/chanzuckerberg/idseq-web/pull/613
