### ISSUE TITLE
Make background white even if there aren't enough samples to fill the screen

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#594]
See attached screenshot - white should go all the way to the bottom of the page. 
![Screen Shot 2018-02-04 at 8.33.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f76b7191a370f111284f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19141c95df74ce94d50a61a3564e4742431.png)

**Comment by cyrielo** [comment]
The issue has been resolved https://github.com/chanzuckerberg/idseq-web/pull/612
