### ISSUE TITLE
speed up deployment

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-web#619]
Currently deploying to production takes down the site for 15 minutes.   After chatting with @ryanking, it seems a few steps can be taken that reduce that time to sub-2 minutes.  Eventually even sub-1 minute.   That could be a game changer in terms of our ability to fix bugs quickly and reducing the penalty for making mistakes.

1.  Turn off rails asset compilation, since most of the site is now compiled in JS.   This will remove the 1 minute penalty for the first request, and the 504 error codes.

2.  Make sure services (resque in particular) respond to SIGKILL, so that we don't have to wait the full timeout to drain them.

3.  Investigate load balancer health check params to make sure there is no unnecessary delays in establishing that a server is up.   In particular, reduce the 60 second drain timeout to 31 seconds;  since we already time out requests after 30 seconds.

**Comment by boris-dimitrov** [comment]
1.  It appears that asset compilation is already turned off, but still for some reason the very first "real" web request takes 30 seconds to return very little.

2. Only during production pushes, it seems the kill signal is SOMETIMES being sent to the wrong container -- the new task container, not the old task container -- so we end up for a very long time in a state where there are 2 new containers running and restarting, and 1 old container sitting idle doing nothing.   Manually killing that old container moves things along.

3.  The health check should be tweaked indeed as it currently accounts for 45 seconds of dead time.    The PUMA server takes 16 seconds to start up, and the next 45 seconds are spent answering trivial health checks.   Any real requests are held back during that 45 second window.   From the user's perspective, the system is just very slow to respond.   After the 45 seconds, the first request from the user is patched through, and it then takes 30 seconds for some rails warmup to succeed.

**Comment by ryanking** [comment]
I think I said this on slack, but it does not appear off to me. See https://github.com/chanzuckerberg/idseq-web/blob/master/config/environments/alpha.rb#L27

**Comment by boris-dimitrov** [comment]
Just adding one more issue here, sometimes instances on ECS become zombified and unavailable for new containers, without AWS noticing for days.   When that happens, the push is very slow or even gets stuck as new containers fail to transition from PENDING to RUNNING when they are accidentally assigned to one of those zombie instances.   The zombie instances can be identified through being inaccessible via SSH.
