### ISSUE TITLE
Public projects should also have members

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#628]
Why is the member list and the ability to add members not showing up on a public project? See screenshot.
![Screen Shot 2018-02-08 at 9.45.07 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454fb6b7191a371f1162e4f5f585edd3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19041c95df743e04c57a41a3761e1712431.png)

**Comment by cdebourcy** [comment]
Member list and "Add User" shows up on public projects if you're admin, but not if you're a random stranger who can view the project only because it's public. I think that's the way it should be, no?

**Comment by cyrielo** [comment]
Yeah because the button is not really tied to project visibility but admin access

**Comment by yunfangjuan** [comment]
Yeah. You have to be a project member to do that.

**Comment by eggerdesigns** [comment]
ok. That makes sense. I would think you would want to see the total number of members but that doesn't matter. Closing this out! Thanks guys.
