### ISSUE TITLE
Style 'forgot password' page

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-web#672]
/users/passwords/new

**Comment by cyrielo** [comment]
@cdebourcy, does this also involve, creating the route for the page? The page does not seem to exist yet.

**Comment by cdebourcy** [comment]
Currently it's the following rails view: app/views/devise/passwords/new.html.erb
You can get to it by logging out and clicking "Forgot password?"
So no need to create a new route

**Comment by eggerdesigns** [comment]
@cyrielo you said this was done right?
