### ISSUE TITLE
refresh browser more often while waiting for results

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-web#677]
after submitting a sample, the browser is stuck in "waiting" and has to be manually refreshed to load the report long after the results from stage 2 have been loaded into the DB

**Comment by cyrielo** [comment]
True, I believe we would need to implement WebSocket real-time connection in rails using rails action cable, otherwise, the fallback option I think will be to continue using the long polling approach @cdebourcy  used for the real-time download update.

**Comment by boris-dimitrov** [comment]
This isn't a realtime feature.   We just need to poll every 60 seconds on a timer.  Doing so is much better than realtime websockets because it can handle situations like the laptop lid being closed or the server going away due to a push of new code.
