### ISSUE TITLE
Remove 'Make project private' option in modal when a project is public

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#741]
Users shouldn't be able to make projects private
![Pasted image at 2018_02_23 11_21 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46d89589378787e986e4be44a11df18069147722713bf3794fd7b068ee1344535e4f3fd153444d04bea6d37ef5f22e7a98595ae8d63b5b22c26945abea854dbf01bc21824785e0bbd95edcfa7f74b9dfd0126754505a9bf54f34a7934acd59ff4fe34454a51a3265ef647b.png)

**Comment by cyrielo** [comment]
This was resolved by Susan
<img width="472" alt="screen shot 2018-03-17 at 6 48 17 pm" src="https://user-images.githubusercontent.com/5603579/37561752-cadd8578-2a13-11e8-80d4-cbdc094a8885.png">
