### ISSUE TITLE
Sample table tooltip, gets obscured when fixed

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#744]
![Screen Shot 2018-02-23 at 8.22.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f06b7191a370f110294f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19e41c95df742e54e55a312316be07f2431.png)

**Comment by cyrielo** [comment]
This issue has been resolved, we switched to the Semantic UI smart popup
