### ISSUE TITLE
Project sidebar scrolling bug

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#745]
After clicking see more and then scrolling up the favorite projects title moves into the header bar.

![image (9).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46e1999b2487c3e1d6a0fd0fe64de29b234324676b5ee17e71d0b42eeb442f050b581cab13585f42fdf0812bf0b16f62964e49bc8f3900299f7744eeaa880dbe06b0218e4e8cb2bf8b4dc9ec3d26ef99c2.png)
![image (10).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46e1999b2487c3e1deb9f601e81fe086264c22703d46f9692584b67fb9167d550b0b49fe460a5f44faf88023a6e03b23984019af80330b2b9b645bf9fa9015ad00b32a8a4a84bfb8894dc1e13b24e3889d02.png)

**Comment by cyrielo** [comment]
Issue Addressed
