### ISSUE TITLE
Add in clear all filters on sample page

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#751]

**Comment by cyrielo** [comment]
@eggerdesigns does clear all basically means reset all i.e make all tissues and host genomes checked again if any unchecked? otherwise, I'm not sure why we want to clear all

**Comment by eggerdesigns** [comment]
@cyrielo yes sorry it's a reset (back to all tissue types checked). Jenn is currently rethinking these tags at the moment too. I agree things are a little weird with a clear all here. probably doesn't make much sense.
