### ISSUE TITLE
Details page background gray should go all the way to bottom of page

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#762]
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65262851f42d2483b72cbb1579560d5f4eaa40515744aafeda39baa47e21d40854b088270a36d43703adbf881eba00b326834a80b7be8f4dc3fa70.png)

**Comment by cyrielo** [comment]
https://github.com/chanzuckerberg/idseq-web/pull/980
