### ISSUE TITLE
Add aggregate score equation to tooltip on report page

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#763]
![Pasted image at 2018_02_23 11_37 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46d89589378787e986e4be44a11df18069147722713bf3794fd7b068ee134452584f3fd153444d04bea6d37ef5f22e7a98595ae8d63b5b22c26945abea854dbf01bc21824785e0bbd95edcfa7f74b9dfd0126754505a9bf54f34a7934acd59ff4de94850ac103f64e2647b.png)

**Comment by cdebourcy** [comment]
I already did this before I left
