### ISSUE TITLE
Weird checkmarks on upload screen

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#768]
![image (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46e1999b2487c3e1dda0fd0fe64de29b234324676b5ee17e71d0b42eeb442f050b581cab13585f42fdf0812bf0b16f62964e49bc8f3900299f7744eeaa880dbe09b0218e4e8cb0b48c4cc2ec3a2ce399c2.png)

**Comment by cyrielo** [comment]
Checkbox css issues have been resolved 
<img width="425" alt="screen shot 2018-03-17 at 6 44 16 pm" src="https://user-images.githubusercontent.com/5603579/37561725-3baa9652-2a13-11e8-9695-67942ee4fa88.png">
