### ISSUE TITLE
Add link to CLI on single upload page

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#780]
It exists on the bulk upload but not the single upload modal.
![image (6).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46e1999b2487c3e1d9a0fd0fe64de29b234324676b5ee17e71d0b42eeb442f050b581cab13585f42fdf0812bf0b16f62964e49bc8f3900299f7744eeaa880dbe08b0218e4e8cb0b58b4dc9e03f23e499c2.png)

**Comment by cdebourcy** [comment]
@jshoe : 
There are two parts to this task. 

(a) When you go to https://idseq.net/samples/bulk_new, there's a line saying "Rather use our CLI? Read documentation here". The text should be replaced by "Rather use our command-line interface? Instructions here" and when you click on "Instructions here", it should open the same modal as when you click on "New sample (command line)" in the top right dropdown.

(b) When you go to https://idseq.net/samples/new, it should have the same line and link: "Rather use our command-line interface? Instructions here"
