### ISSUE TITLE
Rethink term "Infectious Disease Platform"

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-web#822]
I get weird looks every single time I describe the project as an "Infectious Disease Platform" :) Just saw that this is in fact the official description on idseq.net. People seem to think we'd be better off calling it something like "Infectious Disease DIAGNOSTICS Platform" instead ;) Of course we probably don't want to use the term diagnostics. Maybe "Infectious Disease Analysis Platform"?

**Comment by boris-dimitrov** [comment]
How about `Infectious Disease Discovery Platform` ?

**Comment by boris-dimitrov** [comment]
Or `Infectious Disease Discovery and Surveillance Platform`?

**Comment by cdebourcy** [comment]
I love "Discovery"!!!

**Comment by eggerdesigns** [comment]
I love discovery too!!!

**Comment by boris-dimitrov** [comment]
Ok, discovery is great, and for a logo how about the all seeing eye of the egyptian god Horus?   Here is an embroidering rendition which we can tweak with DNA alphabet letters :)

https://www.embroidery-lab.com/product/the-eye-of-horus-free/
