### ISSUE TITLE
Fix sidebar not going all the way to bottom of page

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#855]
![Screen Shot 2018-03-09 at 2.36.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fa6b7191a37af1112d4f5d575ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19141c95df44be74d53a610316be6712431.png)

When you scroll to the bottom of the page the sidebar doesn't take up the whole height of the screen.

**Comment by cyrielo** [comment]
The new sidebar fixed this issue
