### ISSUE TITLE
Update Report Page Design

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#872]
![report-page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46fa918a2c9097e49fe8b846e611b2843b492d762a10e17132d0e27de8442f075b0b1aab135f0d44fcff8822aeb66a77d94e17ff933c0120996048e6edc00db513bb29814e80b4bc824dc0e93521ee8f8d5d73.png)

Make report page look like mock up. 

Change design of Filters, reduce height of header, make download button fixed width (no matter what screen size). Make non selected tab grey instead of black.

**Comment by eggerdesigns** [comment]
@cyrielo List of other things to address here: 
1. Implement consistent dropdown menus and search bars that are based on Semantic UI. Make sure all search boxes and buttons are the same height on the page - based on Jenn's mock. 
2. Update dropdown menu design to be consistent with Jen's mock. Smaller font sizes in dropdown menus. 
3. New report window horizontal size does not scale with window size - it stays fixed to a small size, which is super annoying (in Chrome). Forces user to scroll left and right. Make sure that it has a minimum size but also expands with screen size. 
4. Drop down menus stay "dropped" even when clicking elsewhere in the window. They can only be rolled up by clicking the top of the menu, which is weird.

**Comment by jshoe** [comment]
@eggerdesigns setting the filter to Common Name just seems to gray out the scientific name ones? Is that supposed to happen?

**Comment by cdebourcy** [comment]
It is supposed to show the common names in black, but many taxids don't have a common name, so we still show the scientific name grayed-out

**Comment by cdebourcy** [comment]
If you expand the taxonomy and look through everything, you'll typically find a couple that do have common names

**Comment by eggerdesigns** [comment]
Yes - that is the correct behavior.
