### ISSUE TITLE
Add Phage as an option in the categories dropdown on the report page

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#875]

**Comment by cdebourcy** [comment]
Just wanted to explain that we're currently using "category" synonymously with "superkingdom", and "phage" is not a superkingdom. Therefore adding phage in there seems like an ad-hoc feature request that doesn't generalize to users other than Joe. If it is important for the demo, how about you enter "phage" into the search field? Joe could start to use that feature more, it is very powerful ;)
![screen shot 2018-03-12 at 9 44 29 am](https://user-images.githubusercontent.com/16944816/37297221-5f68f0e4-25da-11e8-9c60-487ab23aa7eb.png)
Thoughts?

**Comment by cdebourcy** [comment]
A more general solution might be to add a filter where you can enter any taxid. But just spending time on singling out phage seems unproductive
