### ISSUE TITLE
Modals not working properly

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-web#888]
![screen shot 2018-03-12 at 4 45 02 pm](https://user-images.githubusercontent.com/16944816/37315040-bbdf87a4-2614-11e8-8cd5-9535aab6c6aa.png)
![screen shot 2018-03-12 at 4 45 19 pm](https://user-images.githubusercontent.com/16944816/37315052-cecc8e70-2614-11e8-9e8e-7c12679018b3.png)

**Comment by jshoe** [comment]
Okay the breaking commit was "6351071 745 cyril project sidebar bug (#840)" :3

@cdebourcy @yunfangjuan

**Comment by jshoe** [comment]
Still looking for what actually changed the style.. the HTML/CSS generated looks practically the same to me except that when you 'inspect element' on the broken version you land on the 'modal-overlay' but the working version lands on 'modal1' like it should. The z-index values are even the same in broken/working version

**Comment by jshoe** [comment]
Okay now I understand how it originated in the sidebar changes b/c the modal is actually embedded in the sidebar for some reason so the ordering layout has changed.

![comparison](https://user-images.githubusercontent.com/5652739/37356386-16589732-26a3-11e8-8f22-a2558e57694a.png)

**Comment by jshoe** [comment]
So removing Sidebar.Pusher and making the inner content a regular div fixes the modals, but then it's obstructed by the Sidebar because Sidebar is meant to be used with Sidebar.Pusher which just pushes the non-sidebar content towards the right

**Comment by cyrielo** [comment]
Hey @jshoe looking into this now

**Comment by cyrielo** [comment]
Okay I just figured this out, the semantic ui rules were more specific than the rule applied to the modal, so basically making the `z-index` of the modal important fixes this. Sorry

**Comment by cyrielo** [comment]
Raising a PR now

**Comment by cyrielo** [comment]
https://github.com/chanzuckerberg/idseq-web/pull/892

**Comment by cdebourcy** [comment]
Nice forensic work @jshoe ! Thanks for raising the PR @cyrielo !

**Comment by cyrielo** [comment]
@jshoe, we wouldn't need  the pusher modal from semantic ui I don't think we desire the overlay effect, so I make the cli modal more prevalent
