### ISSUE TITLE
Can't edit sort headers on 3rd and 4th columns only

### ISSUE THREAD

**Issue by jshoe** [chanzuckerberg/idseq-web#920]
- After setting a new sort filter on the 3rd and 4th columns, you can't seem to click them again. See below:

![mar-14-2018 16-56-21](https://user-images.githubusercontent.com/5652739/37437165-de556106-27a8-11e8-9279-ef85ca2f3dbb.gif)

**Comment by cyrielo** [comment]
Thanks for reporting @jshoe, I've been meaning to fix this as well, basically caused by the Tooltip. Would raise a PR shortly

**Comment by cyrielo** [comment]
https://github.com/chanzuckerberg/idseq-web/pull/923
