### ISSUE TITLE
Grey check-mark appears on sample page after search:

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#928]
Grey check-mark appears on sample page after search

To repro issue: 
Filtered samples down to plasma - selected the only sample available, removed plasma filter and all samples reappeared but the first sample had a grey checkmark
![image (11).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46e1999b2487c3e1deb8f601e81fe086264c22703d46f9692584b67fb9167d550b0b49fe460a5f44faf88023a6e03b23984019af80330b2b9b645bf9fa9015ad03bb2a8a4a87b7bd8f4dc6e83823e2889d02.png)

**Comment by cdebourcy** [comment]
Turns out changing project or filters doesn't seem to remove checkmarks. They just stay in the same location. Am working on a fix
