### ISSUE TITLE
Change hover state of sample name to brand blue (on report page)

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#930]
The arrow should not change the width of the name either and force the name to go to a second line. 

We should also have a max width for the sample names.
![image (12).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46e1999b2487c3e1debbf601e81fe086264c22703d46f9692584b67fb9167d550b0b49fe460a5f44faf88023a6e03b23984019af80330b2b9b645bf9fa9015ad03bb2a8a4a87b7bd8f4dc8ec3d24e68b9d02.png)

**Comment by cyrielo** [comment]
https://github.com/chanzuckerberg/idseq-web/pull/976
