### ISSUE TITLE
Add even padding next to user icon in project info

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#934]
![Screen Shot 2018-03-15 at 3.14.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f66b7191a37bf1132f4f5d565ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a29841c95df44ae04857a41a306be2752431.png)

**Comment by cyrielo** [comment]
Looks more like a missing whitespace actually

**Comment by cyrielo** [comment]
https://github.com/chanzuckerberg/idseq-web/pull/982
