### ISSUE TITLE
Change asset pipeline to use Production versions

### ISSUE THREAD

**Issue by jshoe** [chanzuckerberg/idseq-web#937]
- As reported by Trevor, we're using the development versions of our frontend tools / should change to production compilation. Would probably help speed up performance as well.

React Tools confirms:
"This page is using the development build of React. 🚧

Note that the development build is not suitable for production. 
Make sure to use the production build before deployment.

Open the developer tools, and the React tab will appear to the right."

**Comment by cyrielo** [comment]
Please let's do this, I talked about this before and had a PR to fix the mapping issue caused by the uglificiation.

**Comment by yunfangjuan** [comment]
Trevor is working on this.
