### ISSUE TITLE
Figure out what 'Fake Genus' means in visualization

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#942]
![Screen Shot 2018-03-14 at 5.36.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f76b7191a37df1112d4f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a29841c95df44ae04850ad113160e5722431.png)

**Comment by cdebourcy** [comment]
It means the species didn't have a genus in the taxonomy so we invented a "fake genus" that contains only that species. It wasn't meant to be shown to the user. I think we could hide fake-genus rows. In the report, they are stuffed into "all taxa without genus classification".
