### ISSUE TITLE
Report page tag UI updates

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#952]
Update this text style, text-transform: uppercase; letter-spacing: 1.4px; font-weight: 300
padding: 3px all around. 
Also needs a hover effect on the x (maybe opacity goes to .5?)
![Screen Shot 2018-03-15 at 4.51.06 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f66b7191a37cf1172a4f5f595ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19041c95df44ae04852ad1a326ae1762431.png)

**Comment by sadelokiki** [comment]
done
