### ISSUE TITLE
Make space between dropdown menus on report page consistent

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#953]
![dropdownmenu-space.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46ec869533868cbe81e4ba4db110e384284522316546b3397f8fe62bab0021435a0e4bab175c0940a8ad8e79a1e43c708c5d02e5d13b5827d42103eee9dc4be05ce36ade0d97bcae884dcae93827e68a8a473a1c04198ffc4f78.png)

**Comment by eggerdesigns** [comment]
[Uploading dropdownmenu-space.png...]

**Comment by sadelokiki** [comment]
done
