### ISSUE TITLE
Update header for report/details page

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#955]
![report-page header ui updates.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46fa918a2c9097e49fe8b846e455f5952d4335333c0de33e6081e23cba51394d4d1f0cf31b0d0c00eef39b2ef7b33b268e0a0fb9856a0d73943d11aab98b17bf57bd73995397f4edd4189fb5646fb2c99d452c1c041288fa5f34a19c43cd5ef24fe44d47e9.png)

**Comment by cyrielo** [comment]
https://github.com/chanzuckerberg/idseq-web/pull/967
