### ISSUE TITLE
Category dropdown doesn't close when you click out of dropdown

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#962]
![Screen Shot 2018-03-15 at 8.58.58 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f66b7191a370f117234f5a575ecc3c4a4356bcbbd671f3e57862804e0ebcd46a0970903945f8bfd018ed01ba268a468db6ea8d1fd2f42f67b6d5db1063474f4dcbed5727a19041c95df44ae04a57ac163664e1762431.png)

**Comment by yunfangjuan** [comment]
for now, you have to close the box to close it~

**Comment by eggerdesigns** [comment]
ya that's why it's a bug :)
