### ISSUE TITLE
Change hover button color to IDseq brand blue

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-web#990]
![Screen Shot 2018-03-19 at 11.22.19 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a57f3a52475970011d771e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455fa6b7191a379ee0c2953415e47bc30254d58eeb9cb74fce36f34985619e880685822c26b15f8ec854db853ba208d4e8cbebcdc4b93fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e0495da7143e61e073306e0a.png)

**Comment by sadelokiki** [comment]
done
